
/**
 * Allows the user to guess a random number generated by the computer, from 1-100. 
 * 
 * @author Tushaar Kamat 
 * @version 8/23/16
 */

import java.util.Scanner;
public class GuessingGameV1
{
   public static void main( String [] args )
   {
       //local variables
       Scanner in = new Scanner( System.in );
       int input = 0;
       double randNumDouble = Math.random();
       int counter = 0;
       
       //processing to get proper range
       randNumDouble += 0.01;
       randNumDouble = (int)(randNumDouble * 100);
       int randNum = (int)(randNumDouble);
       
       //while loop for number guessing
       System.out.println( "Try to guess what number I am thinking of (1-100)! " );
       System.out.println();
       
       while ( input != randNum )
       {
           System.out.println( "Enter your guess: " );
           input = in.nextInt();
           
           if ( input < randNum )
           {
               System.out.println( "Too low" );
           }
           else if ( input > randNum )
           {
               System.out.println( "Too High" );
           } 
           else
           {
               System.out.println( "Congratulations!" );
           }
           
           counter++;
       }
       
       //output showing random number and the number of guesses
       System.out.println( "The random number was: " + randNum );
       System.out.println( "Number of guesses: " + counter );
       
   }
   
}
