/**
 * Allows the user to guess a random number generated by the computer, from the range specified.
 *
 * @author Tushaar Kamat
 * @version 8/23/16
 */

import java.util.Scanner;

public class GuessingGameV2 {
    public static void main(String[] args) {
        //local variables
        Scanner in = new Scanner(System.in);
        int input = 0;
        double randNumDouble = Math.random();
        int randNum = 0;
        int lowRange = 0;
        int highRange = 0;
        int counter = 0;

        //processing to get proper range
        System.out.println("Enter two positive, non-zero integers seperated by a space as your range (i.e. 60 120): ");
        System.out.println();
        lowRange = in.nextInt();
        highRange = in.nextInt();
        highRange += 1;
        randNum = (int) (((highRange - lowRange) * randNumDouble) + lowRange);

        //while loop for number guessing
        System.out.println("Try to guess what number I am thinking of! ");
        System.out.println();

        while (input != randNum) {
            System.out.println("Enter your guess: ");
            input = in.nextInt();

            if (input < randNum) {
                System.out.println("Too low");
            } else if (input > randNum) {
                System.out.println("Too High");
            } else {
                System.out.println("Congratulations!");
            }

            counter++;
        }

        //output showing random number and the number of guesses
        System.out.println("The random number was: " + randNum);
        System.out.println("Number of guesses: " + counter);

    }

}
